/**
 * generated by Xtext 2.19.0
 */
package no.hvl.past.corrlang.scoping;

import no.hvl.past.corrlang.scoping.AbstractCorrespondenceLanguageScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class CorrespondenceLanguageScopeProvider extends AbstractCorrespondenceLanguageScopeProvider {
}
