/*
 * generated by Xtext 2.19.0
 */
package no.hvl.past.corrlang.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractCorrespondenceLanguageValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(no.hvl.past.corrlang.correspondenceLanguage.CorrespondenceLanguagePackage.eINSTANCE);
		return result;
	}
}
