/**
 * generated by Xtext 2.19.0
 */
package no.hvl.past.corrlang.validation;

import no.hvl.past.corrlang.validation.AbstractCorrespondenceLanguageValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class CorrespondenceLanguageValidator extends AbstractCorrespondenceLanguageValidator {
}
