/**
 * generated by Xtext 2.19.0
 */
package no.hvl.past.corrlang.ide;

import no.hvl.past.corrlang.ide.AbstractCorrespondenceLanguageIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class CorrespondenceLanguageIdeModule extends AbstractCorrespondenceLanguageIdeModule {
}
