/**
 * generated by Xtext 2.19.0
 */
package no.hvl.past.corrlang.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import no.hvl.past.corrlang.CorrespondenceLanguageRuntimeModule;
import no.hvl.past.corrlang.CorrespondenceLanguageStandaloneSetup;
import no.hvl.past.corrlang.ide.CorrespondenceLanguageIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class CorrespondenceLanguageIdeSetup extends CorrespondenceLanguageStandaloneSetup {
  @Override
  public Injector createInjector() {
    CorrespondenceLanguageRuntimeModule _correspondenceLanguageRuntimeModule = new CorrespondenceLanguageRuntimeModule();
    CorrespondenceLanguageIdeModule _correspondenceLanguageIdeModule = new CorrespondenceLanguageIdeModule();
    return Guice.createInjector(Modules2.mixin(_correspondenceLanguageRuntimeModule, _correspondenceLanguageIdeModule));
  }
}
