/*
 * generated by Xtext 2.19.0
 */
package no.hvl.past.corrlang.ide


/**
 * Use this class to register ide components.
 */
class CorrespondenceLanguageIdeModule extends AbstractCorrespondenceLanguageIdeModule {
}
