/**
 * generated by Xtext 2.19.0
 */
package no.hvl.past.corrlang.correspondenceLanguage.impl;

import no.hvl.past.corrlang.correspondenceLanguage.*;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class CorrespondenceLanguageFactoryImpl extends EFactoryImpl implements CorrespondenceLanguageFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static CorrespondenceLanguageFactory init()
  {
    try
    {
      CorrespondenceLanguageFactory theCorrespondenceLanguageFactory = (CorrespondenceLanguageFactory)EPackage.Registry.INSTANCE.getEFactory(CorrespondenceLanguagePackage.eNS_URI);
      if (theCorrespondenceLanguageFactory != null)
      {
        return theCorrespondenceLanguageFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new CorrespondenceLanguageFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public CorrespondenceLanguageFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case CorrespondenceLanguagePackage.CORRESPONDENCE: return createCorrespondence();
      case CorrespondenceLanguagePackage.CORR_ELEMENT: return createCorrElement();
      case CorrespondenceLanguagePackage.METAMODEL: return createMetamodel();
      case CorrespondenceLanguagePackage.COMMONALITY: return createCommonality();
      case CorrespondenceLanguagePackage.SUB_COMMONALITY: return createSubCommonality();
      case CorrespondenceLanguagePackage.CONSTRAINT: return createConstraint();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Correspondence createCorrespondence()
  {
    CorrespondenceImpl correspondence = new CorrespondenceImpl();
    return correspondence;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public CorrElement createCorrElement()
  {
    CorrElementImpl corrElement = new CorrElementImpl();
    return corrElement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Metamodel createMetamodel()
  {
    MetamodelImpl metamodel = new MetamodelImpl();
    return metamodel;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Commonality createCommonality()
  {
    CommonalityImpl commonality = new CommonalityImpl();
    return commonality;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public SubCommonality createSubCommonality()
  {
    SubCommonalityImpl subCommonality = new SubCommonalityImpl();
    return subCommonality;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Constraint createConstraint()
  {
    ConstraintImpl constraint = new ConstraintImpl();
    return constraint;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public CorrespondenceLanguagePackage getCorrespondenceLanguagePackage()
  {
    return (CorrespondenceLanguagePackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static CorrespondenceLanguagePackage getPackage()
  {
    return CorrespondenceLanguagePackage.eINSTANCE;
  }

} //CorrespondenceLanguageFactoryImpl
