/*
 * generated by Xtext 2.19.0
 */
package no.hvl.past.corrlang


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class CorrespondenceLanguageStandaloneSetup extends CorrespondenceLanguageStandaloneSetupGenerated {

	def static void doSetup() {
		new CorrespondenceLanguageStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
