/*
 * generated by Xtext 2.19.0
 */
package no.hvl.past.corrlang.ui;

import com.google.inject.Injector;
import no.hvl.past.corrlang.CorrespondenceLanguage.ui.internal.CorrespondenceLanguageActivator;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class CorrespondenceLanguageExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(CorrespondenceLanguageActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		CorrespondenceLanguageActivator activator = CorrespondenceLanguageActivator.getInstance();
		return activator != null ? activator.getInjector(CorrespondenceLanguageActivator.NO_HVL_PAST_CORRLANG_CORRESPONDENCELANGUAGE) : null;
	}

}
