/**
 * generated by Xtext 2.19.0
 */
package no.hvl.past.corrlang;

import com.google.inject.Binder;
import no.hvl.past.corrlang.AbstractCorrespondenceLanguageRuntimeModule;
import no.hvl.past.corrlang.generator.OutputConfigurationProvider;
import org.eclipse.xtext.generator.IOutputConfigurationProvider;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class CorrespondenceLanguageRuntimeModule extends AbstractCorrespondenceLanguageRuntimeModule {
  @Override
  public void configure(final Binder binder) {
    super.configure(binder);
    binder.<IOutputConfigurationProvider>bind(IOutputConfigurationProvider.class).to(OutputConfigurationProvider.class);
  }
}
