/**
 * generated by Xtext 2.19.0
 */
package no.hvl.past.corrlang;

import no.hvl.past.corrlang.CorrespondenceLanguageStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class CorrespondenceLanguageStandaloneSetup extends CorrespondenceLanguageStandaloneSetupGenerated {
  public static void doSetup() {
    new CorrespondenceLanguageStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
