<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="BPMN" nsURI="platform:/resource/BPMN/model/BPMN.ecore" nsPrefix="BPMN">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="documentation" value="A simplified metamodel for the BPMN language"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="ProcessVariable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Flow">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//Node"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//Node"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Node" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Activity" abstract="true" eSuperTypes="#//Node">
    <eStructuralFeatures xsi:type="ecore:EReference" name="produces" upperBound="-1"
        eType="#//ProcessVariable"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="consumes" upperBound="-1"
        eType="#//ProcessVariable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="User" eSuperTypes="#//Activity"/>
  <eClassifiers xsi:type="ecore:EClass" name="Service" eSuperTypes="#//Activity"/>
  <eClassifiers xsi:type="ecore:EClass" name="BusinessRule" eSuperTypes="#//Activity"/>
  <eClassifiers xsi:type="ecore:EClass" name="Event" abstract="true" eSuperTypes="#//Node"/>
  <eClassifiers xsi:type="ecore:EClass" name="Start" eSuperTypes="#//Event"/>
  <eClassifiers xsi:type="ecore:EClass" name="End" eSuperTypes="#//Event"/>
  <eClassifiers xsi:type="ecore:EClass" name="Message" eSuperTypes="#//Event">
    <eStructuralFeatures xsi:type="ecore:EReference" name="message" lowerBound="1"
        eType="#//ProcessVariable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Gateway" abstract="true" eSuperTypes="#//Node"/>
  <eClassifiers xsi:type="ecore:EClass" name="And" eSuperTypes="#//Gateway"/>
  <eClassifiers xsi:type="ecore:EClass" name="Or" eSuperTypes="#//Gateway"/>
  <eClassifiers xsi:type="ecore:EClass" name="EventBased" eSuperTypes="#//Gateway"/>
</ecore:EPackage>
