/**
 * generated by Xtext 2.19.0
 */
package no.hvl.past.corrlang.ui;

import no.hvl.past.corrlang.ui.AbstractCorrespondenceLanguageUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class CorrespondenceLanguageUiModule extends AbstractCorrespondenceLanguageUiModule {
  public CorrespondenceLanguageUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
