/**
 * generated by Xtext 2.19.0
 */
package no.hvl.past.corrlang.correspondenceLanguage;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Constraint</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see no.hvl.past.corrlang.correspondenceLanguage.CorrespondenceLanguagePackage#getConstraint()
 * @model
 * @generated
 */
public interface Constraint extends CorrElement
{
} // Constraint
