/**
 * generated by Xtext 2.19.0
 */
package no.hvl.past.corrlang.correspondenceLanguage;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see no.hvl.past.corrlang.correspondenceLanguage.CorrespondenceLanguageFactory
 * @model kind="package"
 * @generated
 */
public interface CorrespondenceLanguagePackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "correspondenceLanguage";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.hvl.no/past/corrlang/CorrespondenceLanguage";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "correspondenceLanguage";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  CorrespondenceLanguagePackage eINSTANCE = no.hvl.past.corrlang.correspondenceLanguage.impl.CorrespondenceLanguagePackageImpl.init();

  /**
   * The meta object id for the '{@link no.hvl.past.corrlang.correspondenceLanguage.impl.CorrespondenceImpl <em>Correspondence</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see no.hvl.past.corrlang.correspondenceLanguage.impl.CorrespondenceImpl
   * @see no.hvl.past.corrlang.correspondenceLanguage.impl.CorrespondenceLanguagePackageImpl#getCorrespondence()
   * @generated
   */
  int CORRESPONDENCE = 0;

  /**
   * The feature id for the '<em><b>Model Space</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CORRESPONDENCE__MODEL_SPACE = 0;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CORRESPONDENCE__ELEMENTS = 1;

  /**
   * The number of structural features of the '<em>Correspondence</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CORRESPONDENCE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link no.hvl.past.corrlang.correspondenceLanguage.impl.CorrElementImpl <em>Corr Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see no.hvl.past.corrlang.correspondenceLanguage.impl.CorrElementImpl
   * @see no.hvl.past.corrlang.correspondenceLanguage.impl.CorrespondenceLanguagePackageImpl#getCorrElement()
   * @generated
   */
  int CORR_ELEMENT = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CORR_ELEMENT__NAME = 0;

  /**
   * The number of structural features of the '<em>Corr Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CORR_ELEMENT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link no.hvl.past.corrlang.correspondenceLanguage.impl.MetamodelImpl <em>Metamodel</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see no.hvl.past.corrlang.correspondenceLanguage.impl.MetamodelImpl
   * @see no.hvl.past.corrlang.correspondenceLanguage.impl.CorrespondenceLanguagePackageImpl#getMetamodel()
   * @generated
   */
  int METAMODEL = 2;

  /**
   * The feature id for the '<em><b>Imported Namespace</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METAMODEL__IMPORTED_NAMESPACE = 0;

  /**
   * The number of structural features of the '<em>Metamodel</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METAMODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link no.hvl.past.corrlang.correspondenceLanguage.impl.CommonalityImpl <em>Commonality</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see no.hvl.past.corrlang.correspondenceLanguage.impl.CommonalityImpl
   * @see no.hvl.past.corrlang.correspondenceLanguage.impl.CorrespondenceLanguagePackageImpl#getCommonality()
   * @generated
   */
  int COMMONALITY = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMONALITY__NAME = CORR_ELEMENT__NAME;

  /**
   * The feature id for the '<em><b>Elements</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMONALITY__ELEMENTS = CORR_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Sub Comms</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMONALITY__SUB_COMMS = CORR_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Commonality</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMONALITY_FEATURE_COUNT = CORR_ELEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link no.hvl.past.corrlang.correspondenceLanguage.impl.SubCommonalityImpl <em>Sub Commonality</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see no.hvl.past.corrlang.correspondenceLanguage.impl.SubCommonalityImpl
   * @see no.hvl.past.corrlang.correspondenceLanguage.impl.CorrespondenceLanguagePackageImpl#getSubCommonality()
   * @generated
   */
  int SUB_COMMONALITY = 4;

  /**
   * The feature id for the '<em><b>Elements</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUB_COMMONALITY__ELEMENTS = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUB_COMMONALITY__NAME = 1;

  /**
   * The number of structural features of the '<em>Sub Commonality</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUB_COMMONALITY_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link no.hvl.past.corrlang.correspondenceLanguage.impl.ConstraintImpl <em>Constraint</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see no.hvl.past.corrlang.correspondenceLanguage.impl.ConstraintImpl
   * @see no.hvl.past.corrlang.correspondenceLanguage.impl.CorrespondenceLanguagePackageImpl#getConstraint()
   * @generated
   */
  int CONSTRAINT = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONSTRAINT__NAME = CORR_ELEMENT__NAME;

  /**
   * The number of structural features of the '<em>Constraint</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONSTRAINT_FEATURE_COUNT = CORR_ELEMENT_FEATURE_COUNT + 0;


  /**
   * Returns the meta object for class '{@link no.hvl.past.corrlang.correspondenceLanguage.Correspondence <em>Correspondence</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Correspondence</em>'.
   * @see no.hvl.past.corrlang.correspondenceLanguage.Correspondence
   * @generated
   */
  EClass getCorrespondence();

  /**
   * Returns the meta object for the containment reference list '{@link no.hvl.past.corrlang.correspondenceLanguage.Correspondence#getModelSpace <em>Model Space</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Model Space</em>'.
   * @see no.hvl.past.corrlang.correspondenceLanguage.Correspondence#getModelSpace()
   * @see #getCorrespondence()
   * @generated
   */
  EReference getCorrespondence_ModelSpace();

  /**
   * Returns the meta object for the containment reference list '{@link no.hvl.past.corrlang.correspondenceLanguage.Correspondence#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see no.hvl.past.corrlang.correspondenceLanguage.Correspondence#getElements()
   * @see #getCorrespondence()
   * @generated
   */
  EReference getCorrespondence_Elements();

  /**
   * Returns the meta object for class '{@link no.hvl.past.corrlang.correspondenceLanguage.CorrElement <em>Corr Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Corr Element</em>'.
   * @see no.hvl.past.corrlang.correspondenceLanguage.CorrElement
   * @generated
   */
  EClass getCorrElement();

  /**
   * Returns the meta object for the attribute '{@link no.hvl.past.corrlang.correspondenceLanguage.CorrElement#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see no.hvl.past.corrlang.correspondenceLanguage.CorrElement#getName()
   * @see #getCorrElement()
   * @generated
   */
  EAttribute getCorrElement_Name();

  /**
   * Returns the meta object for class '{@link no.hvl.past.corrlang.correspondenceLanguage.Metamodel <em>Metamodel</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Metamodel</em>'.
   * @see no.hvl.past.corrlang.correspondenceLanguage.Metamodel
   * @generated
   */
  EClass getMetamodel();

  /**
   * Returns the meta object for the reference '{@link no.hvl.past.corrlang.correspondenceLanguage.Metamodel#getImportedNamespace <em>Imported Namespace</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Imported Namespace</em>'.
   * @see no.hvl.past.corrlang.correspondenceLanguage.Metamodel#getImportedNamespace()
   * @see #getMetamodel()
   * @generated
   */
  EReference getMetamodel_ImportedNamespace();

  /**
   * Returns the meta object for class '{@link no.hvl.past.corrlang.correspondenceLanguage.Commonality <em>Commonality</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Commonality</em>'.
   * @see no.hvl.past.corrlang.correspondenceLanguage.Commonality
   * @generated
   */
  EClass getCommonality();

  /**
   * Returns the meta object for the reference list '{@link no.hvl.past.corrlang.correspondenceLanguage.Commonality#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Elements</em>'.
   * @see no.hvl.past.corrlang.correspondenceLanguage.Commonality#getElements()
   * @see #getCommonality()
   * @generated
   */
  EReference getCommonality_Elements();

  /**
   * Returns the meta object for the containment reference list '{@link no.hvl.past.corrlang.correspondenceLanguage.Commonality#getSubComms <em>Sub Comms</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Sub Comms</em>'.
   * @see no.hvl.past.corrlang.correspondenceLanguage.Commonality#getSubComms()
   * @see #getCommonality()
   * @generated
   */
  EReference getCommonality_SubComms();

  /**
   * Returns the meta object for class '{@link no.hvl.past.corrlang.correspondenceLanguage.SubCommonality <em>Sub Commonality</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Sub Commonality</em>'.
   * @see no.hvl.past.corrlang.correspondenceLanguage.SubCommonality
   * @generated
   */
  EClass getSubCommonality();

  /**
   * Returns the meta object for the reference list '{@link no.hvl.past.corrlang.correspondenceLanguage.SubCommonality#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Elements</em>'.
   * @see no.hvl.past.corrlang.correspondenceLanguage.SubCommonality#getElements()
   * @see #getSubCommonality()
   * @generated
   */
  EReference getSubCommonality_Elements();

  /**
   * Returns the meta object for the attribute '{@link no.hvl.past.corrlang.correspondenceLanguage.SubCommonality#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see no.hvl.past.corrlang.correspondenceLanguage.SubCommonality#getName()
   * @see #getSubCommonality()
   * @generated
   */
  EAttribute getSubCommonality_Name();

  /**
   * Returns the meta object for class '{@link no.hvl.past.corrlang.correspondenceLanguage.Constraint <em>Constraint</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Constraint</em>'.
   * @see no.hvl.past.corrlang.correspondenceLanguage.Constraint
   * @generated
   */
  EClass getConstraint();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  CorrespondenceLanguageFactory getCorrespondenceLanguageFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link no.hvl.past.corrlang.correspondenceLanguage.impl.CorrespondenceImpl <em>Correspondence</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see no.hvl.past.corrlang.correspondenceLanguage.impl.CorrespondenceImpl
     * @see no.hvl.past.corrlang.correspondenceLanguage.impl.CorrespondenceLanguagePackageImpl#getCorrespondence()
     * @generated
     */
    EClass CORRESPONDENCE = eINSTANCE.getCorrespondence();

    /**
     * The meta object literal for the '<em><b>Model Space</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CORRESPONDENCE__MODEL_SPACE = eINSTANCE.getCorrespondence_ModelSpace();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CORRESPONDENCE__ELEMENTS = eINSTANCE.getCorrespondence_Elements();

    /**
     * The meta object literal for the '{@link no.hvl.past.corrlang.correspondenceLanguage.impl.CorrElementImpl <em>Corr Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see no.hvl.past.corrlang.correspondenceLanguage.impl.CorrElementImpl
     * @see no.hvl.past.corrlang.correspondenceLanguage.impl.CorrespondenceLanguagePackageImpl#getCorrElement()
     * @generated
     */
    EClass CORR_ELEMENT = eINSTANCE.getCorrElement();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CORR_ELEMENT__NAME = eINSTANCE.getCorrElement_Name();

    /**
     * The meta object literal for the '{@link no.hvl.past.corrlang.correspondenceLanguage.impl.MetamodelImpl <em>Metamodel</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see no.hvl.past.corrlang.correspondenceLanguage.impl.MetamodelImpl
     * @see no.hvl.past.corrlang.correspondenceLanguage.impl.CorrespondenceLanguagePackageImpl#getMetamodel()
     * @generated
     */
    EClass METAMODEL = eINSTANCE.getMetamodel();

    /**
     * The meta object literal for the '<em><b>Imported Namespace</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference METAMODEL__IMPORTED_NAMESPACE = eINSTANCE.getMetamodel_ImportedNamespace();

    /**
     * The meta object literal for the '{@link no.hvl.past.corrlang.correspondenceLanguage.impl.CommonalityImpl <em>Commonality</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see no.hvl.past.corrlang.correspondenceLanguage.impl.CommonalityImpl
     * @see no.hvl.past.corrlang.correspondenceLanguage.impl.CorrespondenceLanguagePackageImpl#getCommonality()
     * @generated
     */
    EClass COMMONALITY = eINSTANCE.getCommonality();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMMONALITY__ELEMENTS = eINSTANCE.getCommonality_Elements();

    /**
     * The meta object literal for the '<em><b>Sub Comms</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMMONALITY__SUB_COMMS = eINSTANCE.getCommonality_SubComms();

    /**
     * The meta object literal for the '{@link no.hvl.past.corrlang.correspondenceLanguage.impl.SubCommonalityImpl <em>Sub Commonality</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see no.hvl.past.corrlang.correspondenceLanguage.impl.SubCommonalityImpl
     * @see no.hvl.past.corrlang.correspondenceLanguage.impl.CorrespondenceLanguagePackageImpl#getSubCommonality()
     * @generated
     */
    EClass SUB_COMMONALITY = eINSTANCE.getSubCommonality();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SUB_COMMONALITY__ELEMENTS = eINSTANCE.getSubCommonality_Elements();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SUB_COMMONALITY__NAME = eINSTANCE.getSubCommonality_Name();

    /**
     * The meta object literal for the '{@link no.hvl.past.corrlang.correspondenceLanguage.impl.ConstraintImpl <em>Constraint</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see no.hvl.past.corrlang.correspondenceLanguage.impl.ConstraintImpl
     * @see no.hvl.past.corrlang.correspondenceLanguage.impl.CorrespondenceLanguagePackageImpl#getConstraint()
     * @generated
     */
    EClass CONSTRAINT = eINSTANCE.getConstraint();

  }

} //CorrespondenceLanguagePackage
