/**
 * generated by Xtext 2.19.0
 */
package no.hvl.past.corrlang.correspondenceLanguage;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see no.hvl.past.corrlang.correspondenceLanguage.CorrespondenceLanguagePackage
 * @generated
 */
public interface CorrespondenceLanguageFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  CorrespondenceLanguageFactory eINSTANCE = no.hvl.past.corrlang.correspondenceLanguage.impl.CorrespondenceLanguageFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Correspondence</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Correspondence</em>'.
   * @generated
   */
  Correspondence createCorrespondence();

  /**
   * Returns a new object of class '<em>Corr Element</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Corr Element</em>'.
   * @generated
   */
  CorrElement createCorrElement();

  /**
   * Returns a new object of class '<em>Metamodel</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Metamodel</em>'.
   * @generated
   */
  Metamodel createMetamodel();

  /**
   * Returns a new object of class '<em>Commonality</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Commonality</em>'.
   * @generated
   */
  Commonality createCommonality();

  /**
   * Returns a new object of class '<em>Sub Commonality</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Sub Commonality</em>'.
   * @generated
   */
  SubCommonality createSubCommonality();

  /**
   * Returns a new object of class '<em>Constraint</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Constraint</em>'.
   * @generated
   */
  Constraint createConstraint();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  CorrespondenceLanguagePackage getCorrespondenceLanguagePackage();

} //CorrespondenceLanguageFactory
