/*
 * generated by Xtext 2.19.0
 */
package no.hvl.past.corrlang.parser.antlr;

import com.google.inject.Inject;
import no.hvl.past.corrlang.parser.antlr.internal.InternalCorrespondenceLanguageParser;
import no.hvl.past.corrlang.services.CorrespondenceLanguageGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class CorrespondenceLanguageParser extends AbstractAntlrParser {

	@Inject
	private CorrespondenceLanguageGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalCorrespondenceLanguageParser createParser(XtextTokenStream stream) {
		return new InternalCorrespondenceLanguageParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Correspondence";
	}

	public CorrespondenceLanguageGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(CorrespondenceLanguageGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
