/*
 * generated by Xtext 2.19.0
 */
package no.hvl.past.corrlang.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class CorrespondenceLanguageAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("no/hvl/past/corrlang/parser/antlr/internal/InternalCorrespondenceLanguage.tokens");
	}
}
