/*
 * generated by Xtext 2.19.0
 */
package no.hvl.past.corrlang.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractCorrespondenceLanguageScopeProvider extends DelegatingScopeProvider {
}
